"""Migration message

Revision ID: 5d60a14780a0
Revises: 
Create Date: 2019-08-28 10:50:42.746744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d60a14780a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('car_brand', sa.Unicode(), nullable=True),
    sa.Column('body_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
