"""Migration message

Revision ID: 6db2ddb1d65c
Revises: 
Create Date: 2019-09-04 11:04:04.775654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db2ddb1d65c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('owners')
    op.add_column('cars', sa.Column('owner', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'cars', 'users', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_column('cars', 'owner')
    op.create_table('owners',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='owners_pkey')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
